// Generated by Wrangler on Fri Jun 28 2024 11:03:08 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	URLS: KVNamespace;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	JWT_SECRET: string;
	TRACKER: AnalyticsEngineDataset;
	AI: Ai;
}
