// Generated by Wrangler on Tue Jul 09 2024 10:27:20 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	URLS: KVNamespace;
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_API_TOKEN: string;
	JWT_SECRET: string;
	TRACKER: AnalyticsEngineDataset;
	AI: Ai;
}
